name: macOS CLI Test

on:
  workflow_dispatch:   # manual trigger only

jobs:
  test:
    runs-on: macos-latest
    env:
      TERM: xterm-256color
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      MY_APP_MODE: "test"

    steps:
      - uses: actions/checkout@v4

      - name: Show shell versions
        run: |
          echo "Default user shell: $SHELL"
          echo "Bash version at /bin/bash:"
          /bin/bash --version | head -1
          echo "Zsh version:"
          zsh --version

      - name: Install expect
        run: brew install expect
        
      - name: Install pls
        run: |
          echo y | curl -sSL https://raw.githubusercontent.com/cjccjj/pls/main/install.sh | bash
      
      - name: Run interactive script with expect
        run: |
          script -q -e /dev/null ./.github/scripts/simulate_chat.expect

